#config/doctrine/Model.Club.dcm.yml
Model\Club:
    type: entity
    table: club
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 255
            nullable: true
        created:
            type: datetime
            columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    manyToOne:
        created_by:
            targetEntity: Model\User
            joinColumn:
                name: created_by
                referencedColumnName: id
    oneToMany:
        students:
            targetEntity: Model\Student
            mappedBy: club
            cascade: [ "all" ]
